### ISSUE TITLE
Переделай Pear в Peer

### ISSUE THREAD

**Issue by Victide06** [SiegfriedSchmidt/testTrysteroChat#1]
Я пытался найти где это исправить ну и не нашёл. Сам ищи)

**Comment by SiegfriedSchmidt** [comment]
Хех, уже все давно поправил, просто пока не залил)

**Comment by SiegfriedSchmidt** [comment]
Это кстати первая моя закрытая проблема)

**Comment by Victide06** [comment]
И моя первая открытая)
